### ISSUE TITLE
WILL NOT WORK AT ALL, REINSTALLING DOES NOT WORK.

### ISSUE THREAD

**Issue by panic-t** [Bambosh/unofficial-homestuck-collection#334]
**Describe the bug**
A JavaScript error occurred in the main process

Uncaught Exception: 
Error: EPERM:operation not permitted, open 'C:\Program Files\The.Unofficial.Homestuck.Collection-2.0.4-win\Asset Pack V2\archive\_imods.tar'
  at Object.openSync (fs.js:440:3)
  at Object.func [as openSync] (electron/js2c/asar.ls:140:31)
  at Object.writeFileSync (fs.js:1265:35)
  at Object.H [as extractimods] (C:\Program Files\The.Unofficial.Homestuck.Collection-2.0.4-win\resources\app.asar\background.....:76477)
  at Module.<anonymous>(C:\Program Files\The.Unofficial.Homestuck.Collection-2.0.4-win\resources\app.asar\backgro...:12219164)
  at r (C:\Program Files\The.Unofficial.Homestuck.Collection-2.0.4-win\resources\app.asar\background.js:2:110)
  at Object.<anonymous> (C:\Program Files\The.Unofficial.Homestuck.Collection-2.0.4-win\resources\app.asar\backgroun...:229329)
  at r (C:\Program Files\The.Unofficial.Homestuck.Collection-2.0.4-win\resources\app.asar\background.js:2:110)
  at C:\Program Files\The.Unofficial.Homestuck.Collection-2.0.4-win\resources\app.asar\background.js:2:902
  at Object.<anonymous> (C:\Program Files\The.Unofficial.Homestuck.Collection-2.0.4-win\resources\app.asar\background.js:2:913)
  at Module._compile (internal/modules/cjs/loader.js:967:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
  at Module.load (internal/modules/cjs/loader.js:815:32)
  at Module._load (internal/modules/cjs/loader.js:727:14)
  at Function.Modile._load (electron/js2c/asar.js:769:28)
  at Object.<anonymous> (electron/js2c/browser_init.js:205:3376)

**To Reproduce**
downloaded win64 version and the asset pack from media fire
extracted reader to folder in program files
extracted asset folder to same folder
started app
pointed reader to asset pack
got error

**Expected behavior**
the reader to work?

**Screenshots**
![image](https://user-images.githubusercontent.com/100178931/155058520-d665fd6e-6a9a-45d3-ad0a-aff88c037417.png)
![image](https://user-images.githubusercontent.com/100178931/155058580-4b3b2754-1837-4053-9df9-80b8801b6401.png)

**Desktop (please complete the following information):**
 - App V2 i assume?
 - Asset pack V2
 - OS: Windows 10 Home

**Additional context**
will throw this error when i launch the app, but still has background processes running.

**Comment by Niklink** [comment]
Try the bugfix version that was just released, 2.0.5.

**Comment by GiovanH** [comment]
This bug was fixed in the latest release version 2.0.5. You are running 2.0.4
