### ISSUE TITLE
2.0.5 crashes with sharp error

### ISSUE THREAD

**Issue by floorpills** [Bambosh/unofficial-homestuck-collection#336]
on both the published tgz and appimages, as well as compiled from source upon launching the collection program it hangs with 
```
00:42:35.252 (Mods) › Mod choices loaded
00:42:35.254 (Mods) › []
Not disabling hardware acceleration
00:42:35.259 (ElectronMain) › {
  newReader: { current: '006715', limit: '006716' },
  notifications: true,
  subNotifications: true,
  showAddressBar: true,
  urlTooltip: true,
  switchToNewTabs: false,
  forceScrollBar: true,
  hideFullscreenHeader: false,
  smoothScrolling: false,
  pixelScaling: true,
  mspaMode: false,
  bandcampEmbed: true,
  allowSysUpdateNotifs: true,
  devMode: false,
  enableHardwareAcceleration: true,
  themeOverride: 'default',
  themeOverrideUI: 'default',
  forceThemeOverride: false,
  forceThemeOverrideUI: false,
  textOverride: {
    fontFamily: '',
    bold: false,
    fontSize: '0',
    lineHeight: '0',
    paragraphSpacing: true,
    highContrast: false
  },
  arrowNav: true,
  openLogs: false,
  hqAudio: true,
  jsFlashes: true,
  credits: true,
  fastForward: false,
  retcon1: false,
  retcon2: false,
  retcon3: false,
  retcon4: false,
  retcon5: false,
  retcon6: false,
  bolin: false,
  soluslunes: false,
  unpeachy: false,
  pxsTavros: false,
  cursedHistory: false,
  modListEnabled: []
}
last version 2.0.5 gte current version 2.0.5
00:42:35.281 (Resources)    › Resources initialized to http://127.0.0.1:37019/
A JavaScript error occurred in the main process
Uncaught Exception:
Error: 
Something went wrong installing the "sharp" module

libvips-cpp.so.42: cannot open shared object file: No such file or directory

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current linux-x64 runtime: "npm install --platform=linux --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/home/lilith/tmp/unofficial-homestuck-collection/dist_electron/linux-unpacked/resources/app.asar/node_modules/sharp/lib/sharp.js:31:9)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/lilith/tmp/unofficial-homestuck-collection/dist_electron/linux-unpacked/resources/app.asar/node_modules/sharp/lib/constructor.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```
I've tried installing sharp with the commands shown in the error to no avail, not sure why this is happening

**Comment by GiovanH** [comment]
This even happens when you run the development version with `make test`?

**Comment by floorpills** [comment]
> This even happens when you run the development version with `make test`?

`make test` loads fine after removing the previous builds but I'm still getting the error after `make publish`

**Comment by GiovanH** [comment]
What logging output do you get with the commands `npm install --ignore-scripts=false --verbose sharp` and `npm install --platform=linux --arch=x64 sharp`?

Concerning that this is happening even with the appimage.

**Comment by GiovanH** [comment]
@floorpills See if this works: https://github.com/Bambosh/unofficial-homestuck-collection/releases/download/2.0.5/The.Unofficial.Homestuck.Collection-2.0.6-hotfix.AppImage

**Comment by floorpills** [comment]
The hotfix seems to have fixed it, thanks!
