### ISSUE TITLE
"Flash plugin not located" and "No reference to asset directory"

### ISSUE THREAD

**Issue by mozai** [Bambosh/unofficial-homestuck-collection#364]
**Describe the bug**
Two errors in ElectronMain when starting the linux unofficial-homestuck-collection

**To Reproduce**
1. Download unofficial-homestuck-collection-2.0.5.tar.gz
2. `tar xzf unofficial-homestuck-collection-2.0.5.tar.gz && cd unofficial-homestuck-collection-2.0.5
3. `./unofficial-homestuck-collection`

**Expected behavior**
Window opens, prompts me to find the asset pack, or maybe an error about the asset pack not found in an expected place.

**Screenshots**
n/a but here's what I saw on stderr
```
[moses@beatrice unofficial-homestuck-collection-2.0.5]$ ./unofficial-homestuck-collection 
01:51:19.087 (Mods) › modsDir is not defined! First run?
Disabling hardware acceleration
01:51:19.095 (ElectronMain) › {
  newReader: { current: '001901', limit: '001902' },
  notifications: true,
  subNotifications: false,
  showAddressBar: true,
  urlTooltip: true,
  switchToNewTabs: false,
  forceScrollBar: true,
  hideFullscreenHeader: false,
  smoothScrolling: true,
  pixelScaling: true,
  mspaMode: false,
  bandcampEmbed: true,
  allowSysUpdateNotifs: true,
  devMode: false,
  enableHardwareAcceleration: false,
  themeOverride: 'default',
  themeOverrideUI: 'default',
  forceThemeOverride: false,
  forceThemeOverrideUI: false,
  textOverride: {
    fontFamily: '',
    bold: false,
    fontSize: 0,
    lineHeight: 0,
    paragraphSpacing: false,
    highContrast: false
  },
  arrowNav: true,
  openLogs: false,
  hqAudio: true,
  jsFlashes: true,
  credits: true,
  fastForward: false,
  retcon1: true,
  retcon2: true,
  retcon3: true,
  retcon4: true,
  retcon5: true,
  retcon6: true,
  bolin: false,
  soluslunes: false,
  unpeachy: false,
  pxsTavros: false,
  cursedHistory: false,
  modListEnabled: []
}
01:51:19.097 (ElectronMain) › Error: Flash plugin not located at archive/data/plugins/libpepflashplayer.so
    at Module.<anonymous> (/home/moses/Downloads/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:12219924)
    at r (/home/moses/Downloads/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:110)
    at Object.<anonymous> (/home/moses/Downloads/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:229329)
    at r (/home/moses/Downloads/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:110)
    at /home/moses/Downloads/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:902
    at Object.<anonymous> (/home/moses/Downloads/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:913)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Object.<anonymous> (electron/js2c/browser_init.js:205:3376)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:205:3580)
    at __webpack_require__ (electron/js2c/browser_init.js:1:128)
    at electron/js2c/browser_init.js:1:1200
    at electron/js2c/browser_init.js:1:1267
01:51:19.099 (ElectronMain) › Loading check failed, loading setup mode
Deferring app version checks until initial configuration is complete.
(node:256969) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
01:51:20.127 (ElectronMain) › Loading archive
01:51:20.127 (ElectronMain) › Error reloading archive Error: No reference to asset directory
    at F (/home/moses/Downloads/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:12217107)
    at IpcMainImpl.<anonymous> (/home/moses/Downloads/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:12221645)
    at IpcMainImpl.emit (events.js:223:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:173:8161)
    at WebContents.emit (events.js:223:5)
[256969:0326/015120.331296:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)
```

**Desktop (please complete the following information):**
 - software version: 2.0.5
 - Asset Pack Version: n/a, didn't get far enough to use the Asset Pack
 - OS: Linux

**Comment by Hollowsquid** [comment]
I'm commenting to add that it doesn't work with the AppImage either, it produces a similar error

**Comment by VincentKnightTesting** [comment]
~/.config/unofficial-homestuck-
collection/config.json
manually edit this for the asset path, that's where the plugin is

**Comment by avalonv** [comment]
> ~/.config/unofficial-homestuck- collection/config.json manually edit this for the asset path, that's where the plugin is

Sorry, edit what exactly? I'm also having this issue and I'm confused as to whether that is a solution.

**Comment by Hollowsquid** [comment]
> > ~/.config/unofficial-homestuck- collection/config.json manually edit this for the asset path, that's where the plugin is
> 
> Sorry, edit what exactly? I'm also having this issue and I'm confused as to whether that is a solution.

You have to edit the "assetDir" field line 3, and put in there the path to your asset pack

**Comment by ruthslambat** [comment]
I'm having this same issue with both the AppImage and the .tar.gz, but I don't have a config.json file in ~/.config/unofficial-homestuck-collection at all.

**Comment by ryuiro-kitsune** [comment]
> I'm having this same issue with both the AppImage and the .tar.gz, but I don't have a config.json file in ~/.config/unofficial-homestuck-collection at all.

The solution to this seems to be:

1. Delete $HOME/.config/unofficial-homestuck-collection/
2. Launch the tar.gz release (not AppImage for some reason)
3. Edit newly created config.json

I have no idea why the AppImage generated config folder wasn't working.
