### ISSUE TITLE
App doesn't launch on Manjaro Linux

### ISSUE THREAD

**Issue by Hollowsquid** [Bambosh/unofficial-homestuck-collection#369]
**Describe the bug**
Hi, on my Manjaro Linux laptop, the 2.0.5 version fails to launch : when i try to launch the app, i get a black window for a few seconds before diseappearing, which makes running the app impossible (but the previous version (1.1.0 i think ?) worked fine)

Note : i originally encountered this issue with the AUR package [unofficial-homestuck-collection-bin](https://aur.archlinux.org/packages/unofficial-homestuck-collection-bin), but running the app using the tarball yields the same result, so i'm putting this here anyway

**To Reproduce**
1. Download and extract the tar.gz
2. Run `./unofficial-homestuck-collection`
3. See error

**Expected behavior**
The app launching 

**Desktop :**
 - Program version : v2.0.5
 - Asset Pack Version : v2
 - OS : Manjaro Linux

**Additional context**
The error message i get from running `./unofficial-homestuck-collection` : 
```
14:34:19.500 (Mods) › modsDir is not defined! First run?
Disabling hardware acceleration
14:34:19.511 (ElectronMain) › {
  newReader: { current: '001901', limit: '001902' },
  notifications: true,
  subNotifications: false,
  showAddressBar: true,
  urlTooltip: true,
  switchToNewTabs: false,
  forceScrollBar: true,
  hideFullscreenHeader: false,
  smoothScrolling: true,
  pixelScaling: true,
  mspaMode: false,
  bandcampEmbed: true,
  allowSysUpdateNotifs: true,
  devMode: false,
  enableHardwareAcceleration: false,
  useSystemWindowDecorations: false,
  themeOverride: 'default',
  themeOverrideUI: 'default',
  forceThemeOverride: false,
  forceThemeOverrideUI: false,
  textOverride: {
    fontFamily: '',
    bold: false,
    fontSize: 0,
    lineHeight: 0,
    paragraphSpacing: false,
    highContrast: false
  },
  arrowNav: true,
  openLogs: false,
  hqAudio: true,
  jsFlashes: true,
  credits: true,
  fastForward: false,
  retcon1: true,
  retcon2: true,
  retcon3: true,
  retcon4: true,
  retcon5: true,
  retcon6: true,
  bolin: false,
  soluslunes: false,
  unpeachy: false,
  pxsTavros: false,
  cursedHistory: false,
  modListEnabled: []
}
14:34:19.516 (ElectronMain) › Error: Flash plugin not located at archive/data/plugins/libpepflashplayer.so
    at Module.<anonymous> (/home/nora/Téléchargements/unofficial-homestuck-collection-2.0.5/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:12219924)
    at r (/home/nora/Téléchargements/unofficial-homestuck-collection-2.0.5/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:110)
    at Object.<anonymous> (/home/nora/Téléchargements/unofficial-homestuck-collection-2.0.5/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:229329)
    at r (/home/nora/Téléchargements/unofficial-homestuck-collection-2.0.5/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:110)
    at /home/nora/Téléchargements/unofficial-homestuck-collection-2.0.5/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:902
    at Object.<anonymous> (/home/nora/Téléchargements/unofficial-homestuck-collection-2.0.5/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:913)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Object.<anonymous> (electron/js2c/browser_init.js:205:3376)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:205:3580)
    at __webpack_require__ (electron/js2c/browser_init.js:1:128)
    at electron/js2c/browser_init.js:1:1200
    at electron/js2c/browser_init.js:1:1267
14:34:19.519 (ElectronMain) › Loading check failed, loading setup mode
Deferring app version checks until initial configuration is complete.
(node:142683) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
14:34:20.997 (ElectronMain) › Loading archive
14:34:20.998 (ElectronMain) › Error reloading archive Error: No reference to asset directory
    at F (/home/nora/Téléchargements/unofficial-homestuck-collection-2.0.5/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:12217107)
    at IpcMainImpl.<anonymous> (/home/nora/Téléchargements/unofficial-homestuck-collection-2.0.5/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:12221645)
    at IpcMainImpl.emit (events.js:223:5)
    at WebContents.<anonymous> (electron/js2c/browser_init.js:173:8161)
    at WebContents.emit (events.js:223:5)
14:34:21.111 (Mods)         › Got window
[142683:0331/143421.172946:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.
zsh: trace trap (core dumped)  ./unofficial-homestuck-collection
```

**Comment by Hollowsquid** [comment]
Marking it as closed since it seems to be a duplicate of https://github.com/Bambosh/unofficial-homestuck-collection/issues/364, but the issue still persists
