### ISSUE TITLE
Application will not start (Linux)(Pop-OS)

### ISSUE THREAD

**Issue by Neocyberman** [Bambosh/unofficial-homestuck-collection#406]
**To Reproduce**
1. Download 2.0..5.tar.gz
2. Unzip/tar
3. ./unofficial-homestuck-collection
4. See Error

Program was meant to open to perform first time setup, instead a window begins to open and then closes, see attached log.

 - Program version: 2.0.5
 - Graphics Card: AMD RX6800
 - OS: Pop-OS 21.22.04 LTS

{Log as follows}

<pre><font color="#C4A000">11:04:00.033 (Mods)</font> › modsDir is not defined! First run?
Disabling hardware acceleration
<font color="#06989A">11:04:00.038 (ElectronMain)</font> › <b>null</b>
<font color="#CC0000">11:04:00.039 (ElectronMain)</font> › TypeError [ERR_INVALID_ARG_TYPE]: The &quot;path&quot; argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:1039:7)
    at I (/home/kirin/Downloads/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:12219756)
    at Module.&lt;anonymous&gt; (/home/kirin/Downloads/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:12219892)
    at r (/home/kirin/Downloads/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:110)
    at Object.&lt;anonymous&gt; (/home/kirin/Downloads/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:229329)
    at r (/home/kirin/Downloads/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:110)
    at /home/kirin/Downloads/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:902
    at Object.&lt;anonymous&gt; (/home/kirin/Downloads/unofficial-homestuck-collection-2.0.5/resources/app.asar/background.js:2:913)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Object.&lt;anonymous&gt; (electron/js2c/browser_init.js:205:3376)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:205:3580)
<font color="#06989A">11:04:00.039 (ElectronMain)</font> › Loading check failed, loading setup mode
Deferring app version checks until initial configuration is complete.
(node:72452) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
[72452:0710/110400.520559:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn&apos;t usable. Goodbye.
Trace/breakpoint trap (core dumped)
</pre>

**Comment by Kommonwealth** [comment]
Using the argument --in-process-gpu should let it boot for the first time, the argument is not required on subsequent boots.
