### ISSUE TITLE
Flatpak packaging error `The "path" argument must be of type string. Received type undefined`

### ISSUE THREAD

**Issue by Grafcube** [Bambosh/unofficial-homestuck-collection#463]
**Describe the bug**
I'm trying to package TUHC as a flatpak and it almost works. But there's just one problem that I wasn't able to solve so I decided to open a bug report.

**To Reproduce**
1. Clone this repo: https://github.com/Grafcube/unofficial-homestuck-collection-flatpak
2. Install dependency `flatpak install org.electronjs.Electron2.BaseApp/x86_64/22.08`
3. Run `flatpak-builder build dev.bambosh.UnofficialHomestuckCollection.yml --install --user`
4. Run `flatpak run dev.bambosh.UnofficialHomestuckCollection`
5. Error `The "path" argument must be of type string. Received type undefined`

<details>
    <summary>Output log</summary>

    ```
    11:06:38.105 (Mods) › modsDir is not defined! First run?
    Disabling hardware acceleration
    11:06:38.116 (ElectronMain) › null
    11:06:38.120 (ElectronMain) › TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
        at validateString (internal/validators.js:112:11)
        at Object.join (path.js:1039:7)
        at I (/app/unofficial-homestuck-collection/resources/app.asar/background.js:2:12219756)
        at Module.<anonymous> (/app/unofficial-homestuck-collection/resources/app.asar/background.js:2:12219892)
        at r (/app/unofficial-homestuck-collection/resources/app.asar/background.js:2:110)
        at Object.<anonymous> (/app/unofficial-homestuck-collection/resources/app.asar/background.js:2:229329)
        at r (/app/unofficial-homestuck-collection/resources/app.asar/background.js:2:110)
        at /app/unofficial-homestuck-collection/resources/app.asar/background.js:2:902
        at Object.<anonymous> (/app/unofficial-homestuck-collection/resources/app.asar/background.js:2:913)
        at Module._compile (internal/modules/cjs/loader.js:967:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
        at Module.load (internal/modules/cjs/loader.js:815:32)
        at Module._load (internal/modules/cjs/loader.js:727:14)
        at Function.Module._load (electron/js2c/asar.js:769:28)
        at Object.<anonymous> (electron/js2c/browser_init.js:205:3376)
        at Object../lib/browser/init.ts (electron/js2c/browser_init.js:205:3580)
    11:06:38.121 (ElectronMain) › Loading check failed, loading setup mode
    Deferring app version checks until initial configuration is complete.
    /app/bin/run.sh: line 2:     3 Segmentation fault      (core dumped) zypak-wrapper.sh /app/unofficial-homestuck-collection/unofficial-homestuck-collection
    ```
</details>

**Expected behavior**
App starts without issues.

**Desktop (please complete the following information):**
 - 2.0.5
 - OS: Arch Linux / Flatpak Runtime 22.08

**Comment by Grafcube** [comment]
That wasn't the issue at all. I just had to pass `--disable-gpu-sandbox` to electron to get it to work. Sorry for the noise.
