### ISSUE TITLE
["Path" argument must be of type string]  error on pure Wayland install

### ISSUE THREAD

**Issue by swords402** [Bambosh/unofficial-homestuck-collection#496]
**Describe the bug**
See title. Happens right after I launch the program from terminal. I have tried --no-sandbox and --enable-features=UseOzonePlatform --ozone-platform=wayland but neither have changed it.

Program is 2.0.5, this is Appimage ver. Running uptodate arch, wayland, and sway.

```
06:11:15.009 (Mods) › modsDir is not defined! First run?
Disabling hardware acceleration
06:11:15.027 (ElectronMain) › null
06:11:15.033 (ElectronMain) › TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:1039:7)
    at I (/tmp/.mount_The.Unrfgw49/resources/app.asar/background.js:2:12219756)
    at Module.<anonymous> (/tmp/.mount_The.Unrfgw49/resources/app.asar/background.js:2:12219892)
    at r (/tmp/.mount_The.Unrfgw49/resources/app.asar/background.js:2:110)
    at Object.<anonymous> (/tmp/.mount_The.Unrfgw49/resources/app.asar/background.js:2:229329)
    at r (/tmp/.mount_The.Unrfgw49/resources/app.asar/background.js:2:110)
    at /tmp/.mount_The.Unrfgw49/resources/app.asar/background.js:2:902
    at Object.<anonymous> (/tmp/.mount_The.Unrfgw49/resources/app.asar/background.js:2:913)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Object.<anonymous> (electron/js2c/browser_init.js:205:3376)
    at Object../lib/browser/init.ts (electron/js2c/browser_init.js:205:3580)
06:11:15.034 (ElectronMain) › Loading check failed, loading setup mode
Deferring app version checks until initial configuration is complete.
Segmentation fault (コアダンプ)
```

Here's the whole error, incase i am missing something. I am not at all familiar with how java stuff works, so I installed some of the dependencies just cause. Still no dice.

**Comment by GiovanH** [comment]
Everything up to `Loading check failed, loading setup mode` is expected warning trace info for a first startup. Your problem is that Segmentation fault at the end.

**Comment by Aurillium** [comment]
I had the same issue when building from source (tried the AppImage version and the ready-built one on the AUR too with the same results). I don't have Flatpak on my system and I'd rather avoid it where possible because of the space it can take up.

If it helps at all:
OS: Arch Linux
Kernel: Linux 6.2
Window Manager: Hyprland (Wayland, XWayland)
And what I used to build it was what the AUR source package required

**Comment by Aurillium** [comment]
Just did some digging on other issues: using `--in-process-gpu` from #408 fixes it for me
My setup is AMD graphics passed through to a Nvidia GPU which controls the monitors (I'm on a laptop with Nvidia Optimus)
I'm still quite new to all this graphics stuff and I only set things up like this yesterday so I could use a second monitor, so I may have some of this wrong, let me know if you need clarification on anything.
