### ISSUE TITLE
Ubuntu instances of the program never even boot up

### ISSUE THREAD

**Issue by rituales** [Bambosh/unofficial-homestuck-collection#561]
**Describe the bug**
I installed the UHC both through the .tar.gz file found in the assets, and the flatpak route as well. The icon stands in my tray, when I click it, it does nothing. Regardless of the two ways I've tried, the issue remains the same: a wall of text appears telling me something hasn't been set yet, and that it awaits a "first configuration". Something about mods too? 

**To Reproduce**
Trough the zipped tar.gz file: uncompress the file, and try to run it in its folder by running ./unofficial-homestuck-collection.
Through the flatpak installation: I tried running flatpak run unofficial-homestuck-collection.
BUT routes end up with the same wall of text in the terminal.

**Expected behavior**
The program never even opens in the first place.

**Desktop:**
 - Program version: 2.0.7
 - Asset Pack Version: V2 (I did have the same uncompressing situation all Linux seem to be having but 7zip solved it. This is absolutely inconsequential to the issue at hand given that the program doesnt even open in the first place for me to even LOAD the asset pack.
 - OS: Ubuntu 22.04.3 LTS, GNOME 42.9 -- WAYLAND.

**Additional context**
Thank you for reading this so far. I reached out to the folks on the discord server and I tried running their tips but they all add up to the same situation. The program doesn't boot up and the terminal shows the same message. The "--no-sandbox" flag did nothing. The ".config" folder doesnt even exist. Flatpak says the program was installed with no problems. The uncompressing of the tar.gz has no issue whatsoever. I guess I should also mention I'm using a 13-year old computer that until 10 days ago was running Windows 7 from the day it was first purchased. I guess the transition to Ubuntu could have also affected it, but I'm not knowledgeable on the subject. Hope someone can help me reconnect with my teenage self's favorite comic. Thank you for reading!

**Screenshots**
![image2](https://github.com/Bambosh/unofficial-homestuck-collection/assets/75944713/5c905a49-107c-4490-a6db-6cf4817e4301)
![image1](https://github.com/Bambosh/unofficial-homestuck-collection/assets/75944713/8f239385-efcd-4320-a2b3-abf8a2ddb37e)

**Comment by vetens** [comment]
I am having the exact same issue, also with Ubuntu 22.04.2 LTS and GNOME 42.9, though my terminal seems to also output a final line after your line 23 which reads ``[80669:0110/204515.725656:FATAL:gpu_data_manager_impl_private.cc(439)] GPU process isn't usable. Goodbye.``

I am considering building from scratch using the github repo and will update here if that approach yields any success

**Comment by vetens** [comment]
Ok, after trying to build from source I get a similar error with electron (full terminal output). Similar story to the pre-built version, where a window seems to briefly open with electron before closing:

``` 
wren@wrennifer:~/unofficial-homestuck-collection$ make test 
yarn install --ignore-optional
yarn install v1.22.21
[1/4] Resolving packages...
warning electron-builder > app-builder-lib > @electron/universal > asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
warning electron-builder > app-builder-lib > electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ electron-builder install-app-deps
  • electron-builder  version=23.6.0
  • rebuilding native dependencies  dependencies=sharp@0.30.1 platform=linux arch=x64
  • install prebuilt binary  name=sharp version=0.30.1 platform=linux arch=x64 napi=
Done in 16.99s.
touch install
cd src && tar -czf imods.tar imods/
yarn run vue-cli-service electron:serve
yarn run v1.22.21
$ /home/wren/unofficial-homestuck-collection/node_modules/.bin/vue-cli-service electron:serve
 INFO  Starting development server...
40% building 123/148 modules 25 active ...homestuck-collection/node_modules/setimmediate/setImmediate.jsBrowserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
98% after emitting CopyPlugin

 WARNING  Compiled with 5 warnings                                                            10:15:04 PM

 warning  in ./node_modules/prettier/index.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/prettier/index.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/prettier/index.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/prettier/third-party.js

Critical dependency: the request of a dependency is an expression

 warning  in ./node_modules/prettier/parser-typescript.js

Module not found: Error: Can't resolve '@microsoft/typescript-etw' in '/home/wren/unofficial-homestuck-collection/node_modules/prettier'


  App running at:
  - Local:   http://localhost:8080/ 
  - Network: http://192.168.0.142:8080/

  Note that the development build is not optimized.
  To create a production build, run yarn build.

⠹  Bundling main process...

 DONE  Compiled successfully in 2198ms                                                        10:15:07 PM

  File                      Size                     Gzipped

  dist_electron/index.js    15356.48 KiB             7861.38 KiB

  Images and other types of assets omitted.

 INFO  Launching Electron...
22:15:08.810 (Mods) › modsDir is not defined! First run?
Disabling hardware acceleration
22:15:08.823 (ElectronMain) › null
22:15:08.826 (ElectronMain) › TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:1039:7)
    at getFlashPath (webpack:///./src/background.js?:335:24)
    at eval (webpack:///./src/background.js?:347:21)
    at Module../src/background.js (/home/wren/unofficial-homestuck-collection/dist_electron/index.js:3074:1)
    at __webpack_require__ (/home/wren/unofficial-homestuck-collection/dist_electron/index.js:20:30)
    at eval (webpack:///multi_./src/background.js?:1:18)
    at Object.0 (/home/wren/unofficial-homestuck-collection/dist_electron/index.js:3108:1)
    at __webpack_require__ (/home/wren/unofficial-homestuck-collection/dist_electron/index.js:20:30)
    at /home/wren/unofficial-homestuck-collection/dist_electron/index.js:84:18
    at Object.<anonymous> (/home/wren/unofficial-homestuck-collection/dist_electron/index.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
22:15:08.826 (ElectronMain) › Loading check failed, loading setup mode
Deferring app version checks until initial configuration is complete.
22:15:09.044 (ElectronMain) › Vue Devtools failed to install: Error: Loading extension at /home/wren/.config/unofficial-homestuck-collection/extensions/nhdogjmejiglipccpnnnanhbledajbpd failed with: 
Done in 22.44s.
# yarn dev

```

What I did: 

- Install node: ``sudo apt install nodejs``, npm is included per [this answer on stackexchange](https://askubuntu.com/a/462344)

- Install NVM (Node Version Manager) following [these instructions](https://blog.logrocket.com/how-switch-node-js-versions-nvm/), making sure to reset the terminal to propagate the changes this script makes.
- run ``nvm v14.18.3`` to switch out to the node version Bambosh is developing in
- run ``npm install --global yarn`` to install yarn
now that dependancies are sorted, I cloned the repository with  ``git clone https://github.com/Bambosh/unofficial-homestuck-collection.git``
and `cd`-ed in to run ``make test``

What is interesting is that I get the same ``(ElectronMain) › TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined`` error...

[The documentation I could find on this error](https://bobbyhadz.com/blog/typeerror-the-path-argument-must-be-of-type-string#nodejs-typeerror-err_invalid_arg_type-the-path-argument-must-be-of-type-string-received-type-undefined) makes me think that the issue is specifically with configuration, wherein there is an undefined value (to be set by configuration) that is unprotected by a logical OR ``||`` operator which assigns some default value somewhere

**Comment by vetens** [comment]
Ok, Second update: I got it working using the [Flatpak version](https://flathub.org/apps/dev.bambosh.UnofficialHomestuckCollection). there must have been some missing dependancy that the flatpak installs automatically.
