### ISSUE TITLE
Browser does not launch as expected on Linux

### ISSUE THREAD

**Issue by tg5hKVHPyX** [Bambosh/unofficial-homestuck-collection#585]
**Describe the bug**
When I try to run the program, I get an infinitely spinning logo screen. I've left it to run for nearly 10 minutes and nothing has changed. If I try running either packaging format without the `--in-process-gpu` flag, it crashes after flashing a grey window like in other bug reports.

**To Reproduce**
1. Launch through terminal  using`./unofficial-homestuck-collection --in-process-gpu` or `./The-Unofficial-Homestuck-Collection-2.5.0.AppImage --in-process-gpu`
2. Window pops up, infinite spinning logo screen.

**Screenshots**
[Screencast_20240510_191331.webm](https://github.com/Bambosh/unofficial-homestuck-collection/assets/79783324/cb9fca9e-1d7d-436a-8f84-4039e543d796)

**Desktop (please complete the following information):**
 - Program version: 2.5.0
 - Asset Pack Version: V2
 - OS: Linux 6.8.8, Fedora 39 KDE
 - Using Wayland if that matters

**Comment by ifritdiezel** [comment]
exact same issue here. some stuff popped up in the log (with the logo screen on) that seemed relevant 
i'm on linux mint 21.3
```
15:50:52.746 (ElectronMain) › TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:1039:7)
    at getFlashPath (/tmp/.mount_The-UnfWne4P/resources/app.asar/background.js:49746:24)
    at Module.<anonymous> (/tmp/.mount_The-UnfWne4P/resources/app.asar/background.js:49758:21)
    at __webpack_require__ (/tmp/.mount_The-UnfWne4P/resources/app.asar/background.js:26:30)
    at Object.<anonymous> (/tmp/.mount_The-UnfWne4P/resources/app.asar/background.js:17925:18)
    at __webpack_require__ (/tmp/.mount_The-UnfWne4P/resources/app.asar/background.js:26:30)
    at /tmp/.mount_The-UnfWne4P/resources/app.asar/background.js:138:18
    at Object.<anonymous> (/tmp/.mount_The-UnfWne4P/resources/app.asar/background.js:141:10)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
15:50:52.747 (ElectronMain) › Loading check failed, loading setup mode
15:50:52.749 (ElectronMain) › Deferring app version checks until initial configuration is complete.
15:50:52.749 (ElectronMain) › Loading archive
(node:332712) UnhandledPromiseRejectionWarning: Error: No reference to asset directory
    at loadArchiveData (/tmp/.mount_The-UnfWne4P/resources/app.asar/background.js:49676:24)
    at Module.<anonymous> (/tmp/.mount_The-UnfWne4P/resources/app.asar/background.js:49879:3)
    at __webpack_require__ (/tmp/.mount_The-UnfWne4P/resources/app.asar/background.js:26:30)
    at Object.<anonymous> (/tmp/.mount_The-UnfWne4P/resources/app.asar/background.js:17925:18)
    at __webpack_require__ (/tmp/.mount_The-UnfWne4P/resources/app.asar/background.js:26:30)
    at /tmp/.mount_The-UnfWne4P/resources/app.asar/background.js:138:18
    at Object.<anonymous> (/tmp/.mount_The-UnfWne4P/resources/app.asar/background.js:141:10)
    at Module._compile (internal/modules/cjs/loader.js:967:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
(node:332712) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```
